repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.17.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "--output-file", "README.md", "--output-mode", "inject", "./modules/aws/vpc"]
      - id: terraform-docs-go
        args: ["markdown", "--output-file", "README.md", "--output-mode", "inject", "./modules/aws/nat_instance"]
      - id: terraform-docs-go
        args: ["markdown", "--output-file", "README.md", "--output-mode", "inject", "./modules/aws/ecr_private_repo"]
      - id: terraform-docs-go
        args: ["markdown", "--output-file", "README.md", "--output-mode", "inject", "./modules/aws/s3"]

