{
 "title": "Apres Lambda",
 "tags": [
  "Apres",
  "Provisioned"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" },
   {
    "name": "function",
    "label": "Function",
    "query": {}
   },
   { "name": "cloudwatchlogspath", "label": "cloudwatchlogspath", "query": "/apres/lambda/$function" }
  ]
 },
 "panels": [
  {
   "title": "All Functions for region: $region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total invocations [count/sec]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda} MetricName=\"Invocations\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Total error rate [errors/invocations]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expression": "errors / invocations",
     "label": "Error rate",
     "metricEditorMode": 1,
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Total throttle rate [throttles/invocations]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expression": "throttles / invocations",
     "label": "Throttle rate",
     "metricEditorMode": 1,
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "id": "errors",
     "label": "Errors",
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Per function details for function: $function",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Duration per function [average time]  Log scale",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "$function" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\"Duration\"', 'Average', $period))",
     "label": "Duration",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Invocations per function [count/sec]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "$function" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\"Invocations\"', 'Sum', $period))/$period",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Errors per function [count/sec]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "$function" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\"Errors\"', 'Sum', $period))/$period",
     "label": "Errors",
     "metricEditorMode": 1,
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Throttles per function [count/sec]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "$function" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\"Throttles\"', 'Sum', $period))/$period",
     "label": "Throttles",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CloudWatch Logs for $function",
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 100",
       "logGroups": [
        { "arn": "$cloudwatchlogspath", "name": "$cloudwatchlogspath" }
       ],
       "namespace": "AWS/Lambda",
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}