{
 "title": "ECS Cluster",
 "tags": [
  "Apres",
  "Provisioned"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "AWSAccount", "label": "AWS Account", "query": "cloudwatch" },
   { "name": "Region", "query": "regions()" },
   {
    "name": "ECSCluster",
    "query": {}
   },
   {
    "name": "ECSService",
    "label": "ECS Service",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "CPU and Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "$ECSCluster", "ServiceName": "$ECSService" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "$ECSCluster", "ServiceName": "$ECSService" },
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Bytes/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "$ECSCluster", "ServiceName": "$ECSService" },
     "metricName": "NetworkRxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "$ECSCluster", "ServiceName": "$ECSService" },
     "metricName": "NetworkTxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Task Counts",
   "type": "timeseries",
   "description": "Task Counts for the service, ContainerInstanceCount is the number of EC2 Instances running, if any.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$ECSCluster", "ServiceName": "$ECSService" },
     "metricName": "DesiredTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "$ECSCluster", "ServiceName": "$ECSService" },
     "metricName": "PendingTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "$ECSCluster", "ServiceName": "$ECSService" },
     "metricName": "RunningTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "$ECSCluster", "ServiceName": "$ECSService" },
     "metricName": "ContainerInstanceCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Storage Bytes/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "$ECSCluster", "ServiceName": "$ECSService" },
     "metricName": "StorageReadBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "$ECSCluster", "ServiceName": "$ECSService" },
     "metricName": "StorageWriteBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  }
 ]
}