{
 "title": "Grafana Configurator",
 "description": "Apres Grafana Configurator",
 "tags": [ "Apres" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "AWSAccount", "query": "cloudwatch" },
   {
    "name": "LambdaName",
    "label": "LambdaName",
    "query": {}
   },
   {
    "name": "LambdaLogGroup",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard monitors the Grafana Configurator Lambda, created by \nApres's [grafana_managed](https://github.com/apresdev/apres-terraform/tree/main/modules/aws/grafana_managed)\nTerraform module."
   }
  },
  {
   "title": "Lambda Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "dimensions": { "FunctionName": "$LambdaName" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FunctionName": "$LambdaName" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "$LambdaName" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda Logs",
   "type": "table",
   "description": "From CloudWatch Logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 50",
     "logGroups": [
      { "arn": "$LambdaLogGroup", "name": "$LambdaLogGroup" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}