{
 "title": "Landlord",
 "tags": [
  "Apres",
  "Provisioned"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "AWSAccount", "label": "AWS Account", "query": "cloudwatch" },
   { "name": "Region", "query": "regions()" },
   {
    "name": "LandlordAPICluster",
    "label": "Landlord API ECS Cluster Name",
    "query": {}
   },
   {
    "name": "LandlordConsoleCluster",
    "label": "Landlord Console ECS Cluster Name",
    "query": {}
   },
   {
    "name": "LandlordAPIService",
    "label": "Landlord API ECS Service Name",
    "query": {}
   },
   {
    "name": "LandlordConsoleService",
    "label": "Landlord Console ECS Service Name",
    "query": {}
   },
   {
    "name": "LandlordAPILoadBalancer",
    "label": "Landlord API Load Balancer",
    "query": {}
   },
   {
    "name": "APIGateway",
    "label": "API Gateway Name",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Landlord API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This section shows metrics the Landlord API Gateway, which is user-facing."
   }
  },
  {
   "title": "API Gateway Rates",
   "type": "timeseries",
   "description": "Hit Rates. No data means no hits. 2xx rate = Hit - 4XX - 5XX",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "dimensions": { "ApiName": "$APIGateway" },
     "label": "4XX Error Rate",
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ApiName": "$APIGateway" },
     "label": "5XX Error Rate",
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ApiName": "$APIGateway" },
     "label": "Hit Rate",
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "API Gateway Latency",
   "type": "timeseries",
   "description": "Integration Latency is turn around time to the backend. Total Latency includes Integration Latency.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$APIGateway" },
     "label": "Total Latency",
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ApiName": "$APIGateway" },
     "label": "Integration Latency",
     "metricName": "IntegrationLatency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Landlord Console ECS Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
     "options": {
      "content": "This section shows metrics for the Landlord Console service running in ECS."
     }
    },
    {
     "title": "CPU and Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "ClusterName": "$LandlordConsoleCluster", "ServiceName": "$LandlordConsoleService" },
       "metricName": "CpuUtilized",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClusterName": "$LandlordConsoleCluster", "ServiceName": "$LandlordConsoleService" },
       "metricName": "MemoryUtilized",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Network Bytes/second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "dimensions": { "ClusterName": "$LandlordConsoleCluster", "ServiceName": "$LandlordConsoleService" },
       "metricName": "NetworkRxBytes",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClusterName": "$LandlordConsoleCluster", "ServiceName": "$LandlordConsoleService" },
       "metricName": "NetworkTxBytes",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Task Counts",
     "type": "timeseries",
     "description": "Task Counts for the service, ContainerInstanceCount is the number of EC2 Instances running, if any.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "dimensions": { "ClusterName": "$LandlordConsoleCluster", "ServiceName": "$LandlordConsoleService" },
       "metricName": "DesiredTaskCount",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClusterName": "$LandlordConsoleCluster", "ServiceName": "$LandlordConsoleService" },
       "metricName": "PendingTaskCount",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClusterName": "$LandlordConsoleCluster", "ServiceName": "$LandlordConsoleService" },
       "metricName": "RunningTaskCount",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClusterName": "$LandlordConsoleCluster", "ServiceName": "$LandlordConsoleService" },
       "metricName": "ContainerInstanceCount",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Storage Bytes/second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "dimensions": { "ClusterName": "$LandlordConsoleCluster", "ServiceName": "$LandlordConsoleService" },
       "metricName": "StorageReadBytes",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClusterName": "$LandlordConsoleCluster", "ServiceName": "$LandlordConsoleService" },
       "metricName": "StorageWriteBytes",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Landlord API ECS Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
     "options": {
      "content": "This section shows metrics for the Landlord API service running in ECS, including the NLB, which is the target of the API Gateway."
     }
    },
    {
     "title": "ECS CPU and Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "ClusterName": "$LandlordAPICluster", "ServiceName": "$LandlordAPIService" },
       "metricName": "CpuUtilized",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClusterName": "$LandlordAPICluster", "ServiceName": "$LandlordAPIService" },
       "metricName": "MemoryUtilized",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Network Bytes/second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "dimensions": { "ClusterName": "$LandlordAPICluster", "ServiceName": "$LandlordAPIService" },
       "metricName": "NetworkRxBytes",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClusterName": "$LandlordAPICluster", "ServiceName": "$LandlordAPIService" },
       "metricName": "NetworkTxBytes",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Task Counts",
     "type": "timeseries",
     "description": "Task Counts for the service, ContainerInstanceCount is the number of EC2 Instances running, if any.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "dimensions": { "ClusterName": "$LandlordAPICluster", "ServiceName": "$LandlordAPIService" },
       "metricName": "DesiredTaskCount",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClusterName": "$LandlordAPICluster", "ServiceName": "$LandlordAPIService" },
       "metricName": "PendingTaskCount",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClusterName": "$LandlordAPICluster", "ServiceName": "$LandlordAPIService" },
       "metricName": "RunningTaskCount",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClusterName": "$LandlordAPICluster", "ServiceName": "$LandlordAPIService" },
       "metricName": "ContainerInstanceCount",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Storage Bytes/second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "dimensions": { "ClusterName": "$LandlordAPICluster", "ServiceName": "$LandlordAPIService" },
       "metricName": "StorageReadBytes",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClusterName": "$LandlordAPICluster", "ServiceName": "$LandlordAPIService" },
       "metricName": "StorageWriteBytes",
       "namespace": "ECS/ContainerInsights",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Load Balancer Flow Counts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "$LandlordAPILoadBalancer" },
       "metricName": "ActiveFlowCount",
       "namespace": "AWS/NetworkELB",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      },
      {
       "dimensions": { "LoadBalancer": "$LandlordAPILoadBalancer" },
       "metricName": "NewFlowCount",
       "namespace": "AWS/NetworkELB",
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}