{
 "title": "NAT Instances",
 "tags": [ "Apres" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "AWS Account", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "vpc-nat-az1" },
     "label": "${PROP('Dim.AutoScalingGroupName')} ",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "AutoScalingGroupName": "vpc-nat-az2" },
     "label": "${PROP('Dim.AutoScalingGroupName')} ",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "AutoScalingGroupName": "vpc-nat-az3" },
     "label": "${PROP('Dim.AutoScalingGroupName')} ",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "vpc-nat-az1" },
     "label": "${PROP('Dim.AutoScalingGroupName')} ",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "AutoScalingGroupName": "vpc-nat-az2" },
     "label": "${PROP('Dim.AutoScalingGroupName')} ",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "AutoScalingGroupName": "vpc-nat-az3" },
     "label": "${PROP('Dim.AutoScalingGroupName')} ",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Packets In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "vpc-nat-az1" },
     "label": "${PROP('Dim.AutoScalingGroupName')} ",
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "period": "5m",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "AutoScalingGroupName": "vpc-nat-az2" },
     "label": "${PROP('Dim.AutoScalingGroupName')} ",
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "period": "5m",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "AutoScalingGroupName": "vpc-nat-az3" },
     "label": "${PROP('Dim.AutoScalingGroupName')} ",
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "period": "5m",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Packets Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "vpc-nat-az1" },
     "label": "${PROP('Dim.AutoScalingGroupName')} ",
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/EC2",
     "period": "5m",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "AutoScalingGroupName": "vpc-nat-az2" },
     "label": "${PROP('Dim.AutoScalingGroupName')} ",
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/EC2",
     "period": "5m",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "AutoScalingGroupName": "vpc-nat-az3" },
     "label": "${PROP('Dim.AutoScalingGroupName')} ",
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/EC2",
     "period": "5m",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Average"
    }
   ]
  }
 ]
}