# Original source: https://github.com/freight-hub/terraform-modules-demo/
# This workflow depends on the existence of four labels:
# - patch-version
# - minor-version
# - major-version
# - no-version
# and one of those (and only one) must be applied to the PR, and determines which version to bump.
#
name: Build and version Terraform Modules
concurrency: #avoid concurrent runs on label events, might cause issues on super fast commits  ¯\_(ツ)_/¯
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - modules/aws/**
      - modules/github/**
      - .github/workflows/*.yml
      - "!modules/**/CHANGELOG.md"

  pull_request_target:
    types: [closed]
    paths:
      - modules/aws/**
      - modules/github/**
      - .github/workflows/*.yml
      - "!modules/**/CHANGELOG.md"

permissions:
  contents: write
  pull-requests: write
  id-token: write # This is required for requesting the JWT for AWS permissions

jobs:
  detect:
    runs-on: ubuntu-latest
    name: "Detect pull request context"
    outputs:
      changelog-text: ${{ steps.changelog-text.outputs.result }}
      directories: ${{ steps.condense.outputs.result }}
      release-type: ${{ steps.check_pr_label.outputs.release-type}}
      is-merge-event: >-
        ${{ github.event_name == 'pull_request_target'
         && github.event.action == 'closed'
         && github.event.pull_request.merged == true }}
    steps:
      # I'm getting the labels from the API and not the context("contains(github.event.pull_request.labels.*.name, 'Env Promote')") as the labels
      # are added in 2nd API call so they aren't included in the PR context
      - name: Check PR labels
        id: check_pr_label
        env:
          PR_URL: ${{github.event.pull_request.html_url}} #TODO: check if needed (we don't checkout the code..)
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          LABELS=$(gh pr view $PR_URL --json labels  --jq '.labels[]| select((.name=="minor-version") or (.name=="major-version") or (.name=="patch-version") or (.name=="no-version")) |.name')
          NUMBER_OF_LABELS=$(echo "$LABELS" |wc -w)
          if [ "$NUMBER_OF_LABELS" -eq "1" ] ; then
            echo "Found labels: $LABELS"
            echo "release-type=$LABELS" >> $GITHUB_OUTPUT
          elif [ "$NUMBER_OF_LABELS" -gt "1" ] ; then
            echo "::error ::Too many release type labels, choose only one of minor-version, major-version, patch-version, or no-version. Selected labels: $( echo $LABELS | tr '\n' ' ' )"
            exit 1
          else
            echo "::error ::No release type labels found, choose one of minor-version, major-version, patch-version, or no-version."
            exit 2
          fi

      # This isn't ideal in that if we're updating multiple modules (which you shouldn't do tbh)
      # we'll get the changelog several times, and then add one commit per module.
      - name: Get Changelog Text
        id: changelog-text
        uses: actions/github-script@v7
        with:
          script: |
            // if the trigger is dependabot, use the PR title as the changelog
            // context.actor will be the most recent user, dependabot opens a PR and
            // then user xyz adds commits, the actor will be xyx, not dependabot.
            // The pull_request.user.login is the creator of the PR.
            if (context.payload.pull_request.user.login === "dependabot[bot]") {
              title = context.payload.pull_request.title;
              console.log("This PR was opened by Dependabot, using the title as the Changelog: " + title);
              return title;
            }
            changelog = '';
            lines = context.payload.pull_request.body.split('\n');
            // Match all cases of "changelog:"
            const re = /changelog: (.*)/i;
            for(const line of lines) {
              if (re.test(line)) {
                // greedily get everything after the first colon and space
                // sometimes we get a \r in there so trim it off
                changelog = line.split(': ',2)[1].trim();
                break;
              }
            }
            if (changelog === '') {
              // Fail because we should have had a Changelog.
              core.setFailed('No changelog found in PR body! Add a line beginning with "Changelog: " and rerun this job.');
            }
            console.log("Changelog: '" + changelog + "'");
            return changelog;
          result-encoding: string

      - name: Get changed files
        uses: Ana06/get-changed-files@v1.2
        id: raw-files
        with:
          format: "json"
      - name: Condense to directory list
        uses: actions/github-script@v4
        id: condense
        env:
          RAW_FILES: "${{ steps.raw-files.outputs.all }}"
        with:
          # Output is a structure like: { include: [ module_name: "abc", module_directory: 'modules/aws/abc' } ] }
          script: |
            var path = require("path");
            const raw = JSON.parse(process.env.RAW_FILES);

            var modules = new Map();
            for (var item of raw) {

              // Ignore CHANGELOG.md updates.
              if (item.endsWith("/CHANGELOG.md")){
                continue;
              }

              // Determine which module(s) are being updated.
              if (item.startsWith("modules")) {
                dir = path.dirname(item);
                // dir at this point should start with "modules/aws/thing/..."
                // Take the 2nd element else we end up with module names for embedded directories
                parts = dir.split("/");
                module_name = parts[2];
                modules.set( module_name, parts[0] + "/" + parts[1] + "/" + parts[2] );
              }
            }

            module_paths = [];
            for (const key of modules.keys()) {
              module_paths.push({
                module_name: key,
                module_directory: modules.get(key)
              });
            }

            if (module_paths.length < 1) return {};
            return {
              include: module_paths,
            };

  validate:
    needs: detect
    if: ${{ needs.detect.outputs.directories != '{}' }}
    strategy:
      matrix: "${{ fromJson(needs.detect.outputs.directories) }}"
      fail-fast: false
    name: "Validate: ${{ matrix.module_name }}"
    uses: ./.github/workflows/tf-modules-workflow.yml
    secrets: inherit
    with:
      module_directory: ${{ matrix.module_directory }}
      module_name: ${{ matrix.module_name }}

  plan:
    needs: [detect, validate]
    if: ${{ needs.detect.outputs.directories != '{}' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: "${{ fromJson(needs.detect.outputs.directories) }}"
      fail-fast: false
    name: "Plan versions: ${{ matrix.module_name }}"
    steps:
      # Need the code to manage the changelog steps
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect previous version number
        uses: actions/github-script@v4
        id: prev-version
        env:
          PACKAGE_NAME: "${{ matrix.module_name }}"
        with:
          script: |
            const { owner, repo } = context.repo;
            const query = `query($owner: String!, $repo: String!, $refPrefix: String!) {
              repository(owner: $owner, name: $repo) {
                refs(refPrefix: $refPrefix, first: 1, orderBy: {field: TAG_COMMIT_DATE, direction: DESC}) {
                  edges { node { name } }
                }
              }
            }`;
            const result = await github.graphql(query, { owner, repo,
              refPrefix: `refs/tags/rel/${process.env.PACKAGE_NAME}/`,
            });
            const prevNode = result.repository.refs.edges[0];
            const prevVer = prevNode ? prevNode.node.name : '0.0.0';
            console.log('Found previous version', prevVer);
            return prevVer;
          result-encoding: string

      - name: Determine new version number
        uses: actions/github-script@v7
        id: new-version
        env:
          PREV_VERSION: "${{ steps.prev-version.outputs.result }}"
          RELEASE_TYPE: "${{ needs.detect.outputs.release-type }}"
        with:
          script: |
            const { PREV_VERSION, RELEASE_TYPE } = process.env;
            console.log('Previous version was', PREV_VERSION);
            console.log('Release type is', RELEASE_TYPE);

            if (RELEASE_TYPE === 'no-version') {
              console.log('No version bump needed');
              return PREV_VERSION;
            }

            const numbers = PREV_VERSION.split('.');
            const numberIdx = ['major-version', 'minor-version', 'patch-version'].indexOf(RELEASE_TYPE);
            numbers[numberIdx] = parseInt(numbers[numberIdx]) + 1;
            for (let i = numberIdx + 1; i < numbers.length; i++) {
              numbers[i] = 0;
            }
            const newVersion = numbers.join('.');
            console.log('New version is: ', newVersion);
            return newVersion;
          result-encoding: string

      - name: Store version numbers
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mkdir output
          echo '${{ steps.prev-version.outputs.result }}' > output/previous-version.txt
          echo '${{ steps.new-version.outputs.result }}' > output/new-version.txt
          echo '# This file is auto-generated' > ${{ matrix.module_directory }}/module_version.tf
          echo 'locals {' >> ${{ matrix.module_directory }}/module_version.tf
          echo '  module_version = "${{ steps.new-version.outputs.result }}"' >> ${{ matrix.module_directory }}/module_version.tf
          echo '}' >> ${{ matrix.module_directory }}/module_version.tf

      - name: Upload result artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: ${{ matrix.module_name }}
          path: output
          retention-days: 5

      # Use the changelog text from the PR body, parsed in the detect job.
      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ steps.new-version.outputs.result }}
          # Get release notes from the detect job output
          release-notes: ${{ needs.detect.outputs.changelog-text }}
          path-to-changelog: ${{ matrix.module_directory }}/CHANGELOG.md

      - name: Commit with signed
        uses: planetscale/ghcommit-action@v0.1.6
        with:
          commit_message: "Update ${{ matrix.module_name }} CHANGELOG"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
          file_pattern: "${{ matrix.module_directory }}/CHANGELOG.md ${{ matrix.module_directory }}/module_version.tf"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  comment:
    needs: [detect, plan]
    if: needs.detect.outputs.is-merge-event == 'false'
    runs-on: ubuntu-latest
    name: "Comment on PR"
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          path: outputs

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: outputs

      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const { number: issue_number } = context.issue;
            const { readdir, readFile } = require('fs').promises;
            const utf8 = { encoding: 'utf-8' };

            const lines = [
              '# Release plan', '',
              '| Directory | Previous version | New version |',
              '|--|--|--|',
            ];
            const sections = [];

            for (const folder of await readdir('outputs', { withFileTypes: true })) {
              console.log("Looking at folder: ", folder.name);
              if (!folder.isDirectory()) continue;
              const readText = (name) => readFile(name, utf8).then(x => x.trim());

              lines.push('| '+[
                `\`${folder.name}\``,
                `${await readText(`outputs/${folder.name}/previous-version.txt`)}`,
                `**${await readText(`outputs/${folder.name}/new-version.txt`)}**`,
              ].join(' | ')+' |');

            }

            const finalBody = [lines.join('\n'), ...sections].join('\n\n');

            // Comments on PR's are issue comments, even though that looks odd.
            const {data: allComments} = await github.rest.issues.listComments({ issue_number, owner, repo });
            const ourComments = allComments
              .filter(comment => comment.user.login === 'github-actions[bot]')
              .filter(comment => comment.body.startsWith(lines[0]+'\n'));

            const latestComment = ourComments.slice(-1)[0];
            if (latestComment && latestComment.body === finalBody) {
              console.log('Existing comment is already up to date.');
              return;
            }

            const {data: newComment} = await github.rest.issues.createComment({ issue_number, owner, repo, body: finalBody });
            console.log('Posted comment', newComment.id, '@', newComment.html_url);
            // Delete all our previous comments
            for (const comment of ourComments) {
              if (comment.id === newComment.id) continue;
              console.log('Deleting previous PR comment from', comment.created_at);
              await github.rest.issues.deleteComment({ comment_id: comment.id, owner, repo });
            }

  trigger-release:
    needs: [detect, plan]
    if: needs.detect.outputs.is-merge-event == 'true'
    runs-on: ubuntu-latest
    name: "Dispatch release event"
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          path: outputs

      - name: Combine version information
        id: extract-releases
        uses: actions/github-script@v2
        with:
          script: |
            const { readdir, readFile } = require('fs').promises;
            const utf8 = { encoding: 'utf-8' };
            const readText = (name) => readFile(name, utf8).then(x => x.trim());

            const directories = await readdir('outputs', { withFileTypes: true });
            return await Promise.all(directories
              .filter(x => x.isDirectory())
              .map(async folder => ({
                module: folder.name,
                prevVersion: await readText(`outputs/${folder.name}/previous-version.txt`),
                newVersion: await readText(`outputs/${folder.name}/new-version.txt`),
              })));

      - name: Tag Versions
        uses: actions/github-script@v2
        env:
          RELEASE_LIST: "${{ steps.extract-releases.outputs.result }}"
        with:
          script: |
            const { owner, repo } = context.repo;
            const sha = context.sha;
            const releases = JSON.parse(process.env.RELEASE_LIST);
            for (const release of releases) {
              const tagName = `rel/${release.module}/${release.newVersion}`;

              const ref = `refs/tags/${tagName}`;
              console.log('Tagging', tagName, 'as', sha);
              await github.git.createRef({ owner, repo, ref, sha });
            }
