name: validate-terraform-module

# This workflow takes a Terraform module, validates that format and syntax are correct,
# and runs checkov to check for security issues. It updates docs using terraform-docs on the README.md file.

on:
  workflow_call:
    inputs:
      module_directory:
        description: Working directory of the Terraform module
        required: true
        type: string
      checkov_skip_path:
        description: Path relative to the module_directory skip.
        required: false
        type: string
      module_name:
        description: Name of the module, used for getting the version from the commit message, see README.md for details.
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.module_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Needed for versioning
          fetch-depth: 0

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.7.1

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check

      # Setup GitHub Credentials for Terraform/Tofu to import modules from apresdev/apres-terraform
      - name: Setup GitHub Creds
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://x-access-token:${{ secrets.APRESDEV_RTKMHART_TOKEN }}@github.com

      - name: OpenTofu Init
        id: init
        run: pwd && tofu init -no-color

      - name: OpenTofu Validate
        id: validate
        run: pwd && tofu validate -no-color

      - name: Set up Python 3.8 for Checkov
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ inputs.module_directory }}
          framework: terraform
          output_format: cli
          skip_path: ${{ inputs.checkov_skip_path }}

      # Not every module has a tests directory, so we guard the rest of the steps with the if line.
      - name: Install go
        if: ${{ hashFiles(format('{0}/tests', inputs.module_directory)) != '' }}
        uses: actions/setup-go@v1
        with:
          go-version: 1.21

      - name: Install go modules
        if: ${{ hashFiles(format('{0}/tests', inputs.module_directory)) != '' }}
        working-directory: "${{ inputs.module_directory }}/tests"
        run: go mod download

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381491850865:role/GitHubActionsDeployerRole-apresdev-apres-terraform
          role-session-name: GitHub_AWS_OIDC_apresdev-apres-terraform
          aws-region: us-east-2

      - name: Run terratest
        if: ${{ hashFiles(format('{0}/tests', inputs.module_directory)) != '' }}
        working-directory: "${{ inputs.module_directory }}/tests"
        # Override timeout, some infrastructure takes time to build and destroy
        run: go test -v -timeout 30m
