# Current Identity
data "aws_caller_identity" "current" {}

# Current Region
data "aws_region" "current" {}

# Lookup the code signing bucket
data "aws_kms_alias" "lambda_artifacts" {
  name = "alias/aws/lambda"
}

data "aws_vpc" "default" {
  count = local.use_vpc ? 1 : 0

  tags = {
    Name        = "Workload VPC ${var.vpc.environment_tag}",
    environment = var.vpc.environment_tag
  }
}

# Lookup private subnets for the VPC. This gets back a list of subnet IDs.
data "aws_subnets" "private" {
  count = local.use_vpc ? 1 : 0

  tags = {
    environment = var.vpc.environment_tag
    subnet-tier = "private"
  }
}

# Now get the details for each subnet we found so we can get the CIDR blocks.
# This gets back the full details for each subnet, like the DescribeSubnets API call.
# https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSubnets.html
data "aws_subnet" "private" {
  for_each = toset(local.use_vpc ? data.aws_subnets.private[0].ids : [])
  id       = each.value
}

# create the parameters here to deal with dependencies in the regional lambda module.
locals {
  code_signing_config_arn   = var.code_signing_arn_ssm_parameter == "" ? "/apres/lambda/signing-config-arn" : var.code_signing_arn_ssm_parameter
  code_signing_profile_name = var.code_signing_name_ssm_parameter == "" ? "/apres/lambda/signing-profile-name" : var.code_signing_name_ssm_parameter
}

# Load the SSM paramter that contains the signing config ARN generated by the regional lambda module.
data "aws_ssm_parameter" "signing_config_arn" {
  count = var.disable_code_signing ? 0 : 1
  name  = local.code_signing_config_arn
}

# Load the SSM paramter that contains the signing config ARN generated by the regional lambda module.
data "aws_ssm_parameter" "signing_profile_name" {
  count = var.disable_code_signing ? 0 : 1
  name  = local.code_signing_profile_name
}
